#@ load("@ytt:data", "data")
#! This is the template for services 

version: #@ data.values.version

services:
  #@ for/end service in data.values.services:
  - container_name: #@ service.container_name
    image: #@ service.image
    restart: #@ service.restart
    ports: #@ service.ports
    environment: #@ service.environment



